conffile = "my.cnf"
[[group]]
identifier	=	"client"
	[[group.pair]]
	key		=	"port"
	value	=	"3306"

	[[group.pair]]
	key		=	"socket"
	value	=	"/var/run/mysqld/mysqld.sock"

[[group]]
identifier	=	"mysqld_safe"
	[[group.pair]]
	key		=	"socket"
	value	=	"/var/run/mysqld/mysqld.sock"

	[[group.pair]]
	key		=	"nice"
	value	=	"0"

[[group]]
Identifier	=	"mysqld"
	[[group.pair]]
	key		=	"name"
	value	=	"mysql"

	[[group.pair]]
	key		=	"pid-file"
	value	=	"/var/run/mysqld/mysqld.pid"
