
[configuration]
conffile = "my.cnf"
[[group]]
identifier	=	"client"
	[group.port]
	key		=	"port"
	value	=	3306

	[group.socket]
	key		=	"socket"
	value	=	"/var/run/mysqld/mysqld.sock"

[[group]]
identifier	=	"mysqld_safe"
	[group.socket]
	key		=	"socket"
	value	=	"/var/run/mysqld/mysqld.sock"

	[group.nice]
	key		=	"nice"
	value	=	0

[[group]]
identifier	=	"mysqld"
	[group.name]
	key		=	"name"
	value	=	"mysql"

	[group.pidfile]
	key		=	"pid-file"
	value	=	"/var/run/mysqld/mysqld.pid"
